### ISSUE TITLE
rename to ulisp-esp8266.ino to match the directory name?

### ISSUE THREAD

**Issue by drawkula** [technoblogy/ulisp-esp8266#1]
The Arduino software still does not like sketches to be named differently than the surrounding folder (or am I overlooking an option?) and renaming this sketch's folder to `ulisp` would conflict with the one I have for playing with uLisp on a 1284er.

Can you please think some milliseconds about renaming this sketch to `ulisp-esp8266.ino`?

...or is having git repositories in the sketches directory a completely bad idea?

**Comment by technoblogy** [comment]
Good suggestion - I'll do it.

**Comment by drawkula** [comment]
Thanks! That makes life easier...
